### ISSUE TITLE
Cycles node editor

### ISSUE THREAD

**Issue by dilom** [Dancovich/libgdx_blender_g3d_exporter#11]
Is it possible to include Cycles Render and node editor materials export in the future? Are there any limitations using such complex materials in libgdx?

**Comment by Dancovich** [comment]
libGDX doesn't have built in features to render anything like Cycles. Also isn't Cycles a ray tracing engine? libGDX doesn't do ray tracing out of the box.

Since it's OpenGL EX 2+ one could write shaders to simulate Cycles materials but you would have to find those shaders online or write them yourself.

Also the G3D format only support referencing raster bitmap files as textures, it doesn't support procedural materials or anything like that. If you could write a shader in libGDX the G3D file would still just contain the model, bones, textures and light information (diffuse color, specular color and such). You would have to load the model and fine tune the shader to replicate what you did in Blender.

So your best bet would be to bake the materials in Blender to normal texture files (assuming you're not using fancy animated materials) and apply the baked textures to your model before exporting.

**Comment by dilom** [comment]
Yes, I think I will go with baking for now. 

The main issue that I am facing is that there is a lot of hit and miss with exports currently. It seems like half of the time the mesh becomes too much for libgdx to handle and the other half of the time the materials are too complicated. I can work around that but I wish there was a way to eliminate much of that experimentation and guess work and just go with what works regardless of the limitations.

I am planning on checking BDX and Mundus and see if they can limit me to only the 3D stuff that overlaps Blender and libgdx. 

Thanks for working on the exporter it definitely makes life easier. May be the only suggestion I have is that the tool can give some quick info on the export page to let the user know what will be included/not included in the g3d file.
