### ISSUE TITLE
Export doesn't include animations

### ISSUE THREAD

**Issue by dilom** [Dancovich/libgdx_blender_g3d_exporter#9]
I tried exporting the default blender scene with the cube and it works great. However when I add LocRotScale keyframe to frame 1, then scale and add another LocRotScale keyframe to the last frame and export it, there are no animations listed in the g3dj file, same result in the g3db file. The cube still shows fine. The animation works in blender. I tried playing a little with the Action Editor / Fake User in Dope View but couldn't get it to work that way either. What am I missing? Thanks

**Comment by Dancovich** [comment]
The exporter doesn't support keyframes directly set in the mesh object because G3D format also doesn't support this. The G3D format only supports bone animation.

To achieve what you want, create a new armature with a single bone _(**Shift+A > Armature > Single Bone**)_, attach it to the cube object _(select the object first then **Shift+RMB** on the armature object **> Ctrl+P > Armature With Automatic Weights**)_ and do the exact steps you just did (keyframe on frame 1, go to last frame, scale and keyframe again) but on the bone instead of the mesh object. Remember to scale the bone in pose mode, not in object or edit mode.

Below is an example file with this setup for you to test. Notice that when exporting this file you'll just see two keyframes on the resulting file (as expected) but a new file on Blender will produce 250 keyframes. That's because by default Blender uses a bezier curve to ease animations and since LibGDX only supports linear interpolation we have to generate multiple keyframes to simulate the easing effect. If you set the animation interpolation to linear in Blender this will produce the same keyframes you set on your file.

[animated_cube.zip](https://github.com/Dancovich/libgdx_blender_g3d_exporter/files/530312/animated_cube.zip)

**Comment by dilom** [comment]
Thank you! First time playing with G3D and it wasn't very clear it has to bone only animation from all the places I was reading. Thanks again
